### ISSUE TITLE
Closed accordion arrows start out pointing up when they should point down

### ISSUE THREAD

**Issue by csrs** [DjangoGirls/tutorial#1122] opened 2017-09-29 04:32 UTC
### Issue description

This is an issue with the UI of the tutorial accordions.

On pages with accordions (for example, https://tutorial.djangogirls.org/en/intro_to_command_line/) the accordions start with the arrow pointing up, which could be confusing to users who don't know how they work and don't know that the arrow indicates if the accordion can open or close. Generally a closed accordion has an arrow pointing down, indicating that a user can expand it down to open it up. Once you open and close the accordion the first time the arrows switch the way a user would expect.

### Language

English language guide

### Operating system

Any operating system

**Comment by aniav** [comment] 2017-09-30 21:44
This is a duplicate of #965

**Closed by aniav** 2017-09-30 21:44 UTC
