### ISSUE TITLE
Error on Deploy to Python Anywhere

### ISSUE THREAD

**Issue by pyBell** [DjangoGirls/tutorial#1098] opened 2017-08-30 20:51 UTC
EN:
Where: https://tutorial.djangogirls.org/pt/html/
When you send site from github to python anywhere for the first time, you'll get an error that states your host is not allowed. To solve this, just add the URL's string for your site "username.pythonanywhere.com" inside the variable ALLOWED_HOSTS at mysite/settings.py

PT:
Onde: https://tutorial.djangogirls.org/pt/html/
Quando tu manda o site pro python anywhere pela primeira vez, sempre dá um erro dizendo que o host não está habilitado. Aí é só adicionar o nome do site "username.pythonanywhere.com" na variável ALLOWED_HOSTS do arquivo mysite/settings.py

**Comment by arthru** [comment] 2017-09-12 08:15
This is a duplicate of #1002

**Comment by rsip22** [comment] 2017-09-21 16:49
This has been fixed in the Portuguese version with PR #955 , now it shows:

`mysite/settings.py

ALLOWED_HOSTS = ['127.0.0.1', '<your_username>.pythonanywhere.com']`

**Closed by rsip22** 2017-09-21 16:49 UTC
