### ISSUE TITLE
Truncation of post text in post list

### ISSUE THREAD

**Issue by MichaelClerx** [DjangoGirls/tutorial#1189] opened 2017-12-12 14:37 UTC
The first examples of what the website is going to look like show truncated posts on the first page (the post list). This makes sense, because otherwise why have the post_detail pages?

As far as I can see though, code for truncating these posts is never introduced (although it's visible on https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/content/en/homework/)

Maybe this should be introduced on https://tutorial.djangogirls.org/en/extend_your_application/ ?

**Comment by ekohl** [comment] 2018-01-18 23:08
That would be a good addition. A PR would be very welcome.

**Comment by ekohl** [comment] 2018-11-17 11:39
Closing as a duplicate of https://github.com/DjangoGirls/tutorial/issues/991

**Closed by ekohl** 2018-11-17 11:39 UTC
Labels: help wanted, status: accepted
