### ISSUE TITLE
Possible incorrect installation tutorial for Linux

### ISSUE THREAD

**Issue by ghost** [DjangoGirls/tutorial#1259] opened 2018-05-07 09:59 UTC
### Issue description

Installation instructions for Linux may be incorrect. Most of the Linux distributions have Python pre-installed. It is a one of the Linux development languages. So, it is important, that only the current version is installed globally. 

Your installation instructions [here](https://tutorial.djangogirls.org/en/installation/) proposes to install a version 3.6 of Python globally. The problem here is that if the system has already another Python version installed, it may break the normal OS work.

I would suggest to change that part of the tutorial to something described in [this post](https://www.caseylabs.com/how-to-create-a-python-3-6-virtual-environment-on-ubuntu-16-04/).

I tested it myself on Ubuntu 16.04 and it works great.

### Language

Is this related to a specific language of the tutorial? **No**

### Operating system

What operating system does this issue relate to? **Linux**

**Comment by ekohl** [comment] 2018-05-07 10:36
That particular blog post doesn't load for me, but I think it makes sense to change it to `apt install python3`. Should we consider this a duplicate of https://github.com/DjangoGirls/tutorial/issues/1222? A PR would be very welcome.

**Comment by alevikpes** [comment] 2018-05-07 10:57
It seems to be currently down. Please, visit it later.

The idea is that any other version of Python must be run in a virtual environment. There is a description in that article about how to do it.

I found also [this description](https://askubuntu.com/a/865569), which explains the same.

**Comment by jhodgdon-drp** [comment] 2018-08-20 21:03
It would also be helpful to say which versions of Python would work for the Linux installation.

In the Windows install instructions, it says that if you have an older version of Windows, you can install an older version of Python. If this is OK to do, then probably an older version of Python would work for Linux as well? For instance, my machine already had Python 3.5.x -- would that be OK? That is what I currently have (from the python3 package).

Incidentally, the instructions for Ubuntu saying
````
sudo apt install python3.6
````
are no good on Ubuntu 16.04.5 LTS.  I got:
````
E: Unable to locate package python3.6
````
So... I'm in favor of changing it to use package python3. This package exists. But for me, it's currently on python 3.5.1 and it says that is the latest version for my current Ubuntu installation, so that needs to be dealt with.

**Comment by jhodgdon-drp** [comment] 2018-08-20 21:04
Oh, the python3.6 package not available bug is #1222 sorry for the noise. But the same PR would fix both I think.

**Comment by jhodgdon-drp** [comment] 2018-08-21 14:53
That pull request should take care of the issue, plus #1222 as well.

**Comment by jhodgdon-drp** [comment] 2018-08-22 19:30
I closed the earlier pull request and substituted this new one, which should take care of 3 related issues.

**Closed** 2018-11-05 15:30 UTC
