### ISSUE TITLE
Tutorial GitBook does not resolve to type=pdf but shows binary after long delay. 

### ISSUE THREAD

**Issue by AnneTheAgile** [DjangoGirls/tutorial#464] opened 2015-08-23 00:45 UTC
hi! the gitbook url doesn't provide pdf but rather a binary, here ; https://www.gitbook.com/download/pdf/book/djangogirls/djangogirls-tutorial?lang=en
Is this the right place to tell someone about that? 

Also, where can I go to get an [old?] copy? 
ty! 
AnneTheAgile

**Comment by williln** [comment] 2015-08-23 01:26
Hi @AnneTheAgile! The link you posted works fine for me. I'd be happy to email you a copy of the PDF, though. Just email me at lacey@djangogirls.org 

What OS and browser are you using?

**Comment by aniav** [comment] 2015-09-14 14:29
This might have been a temporary issue of gitbook. I have just checked and I can't reproduce this issue. Closing for now, feel free to reopen when it occurs again :)

**Closed by aniav** 2015-09-14 14:29 UTC

**Comment by AnneTheAgile** [comment] 2015-09-16 00:01
woo hoo, today that URL does resolve! I had the same issue on another site's gitbook so maybe there is something later we'll figure out.
