### ISSUE TITLE
The ~ doesn't work on pythonanywhere.com with Safari on macOS

### ISSUE THREAD

**Issue by pts** [DjangoGirls/tutorial#1053] opened 2017-06-06 14:20 UTC
The tutorial step https://tutorial.djangogirls.org/en/deploy/#creating-a-virtualenv-on-pythonanywhere mentions typing or copy-pasting a `~` into a pythonanywhere.com Bash console. Unfortunately both typing and copy-pasting are impossible when done in Safari on macOS. We've tried it with a German keyboard layout, and it didn't work.

My suggestion: 1. Recommend Chrome or Firefox in the tutorial. 2. Explicitly mention the error message displayed when the tilde is missing.

**Comment by aniav** [comment] 2017-06-16 09:14
I am not sure I understand what you mean? I have just done a few tests and there are no problems copy-pasting as well as typing ~ in the pythonwnywhere console.

**Comment by ekohl** [comment] 2017-06-16 09:16
Could this be related to a keyboard layout that's different and not mapped properly by safari?

**Comment by aniav** [comment] 2017-06-16 09:22
The German layout is different only with Z and Y being swapped, `~` is in the same place. Signs on the right of the keyboards are umlauts, so this basically should not be related. But I hope to get more clarification on this one :)

**Comment by pts** [comment] 2017-06-16 12:36
FYI Typing and copy-pasting a `~` to a pythonanywhere.com Bash console didn't work for us in Safari on macOS with a German keyboard layout in March 2017. We solved it by doing it in Chrome instead.

**Comment by aniav** [comment] 2017-09-17 16:55
I have to close it as I was unable to reproduce. If you ever find a way to reproduce please reopen this issue 👍

**Closed by aniav** 2017-09-17 16:55 UTC
